version: '3.1'

services:
  metabase:
    build: .
    ports:
      - 3000:3000
    volumes:
      - metabase_data:/metabase.db
  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: metabase
      MYSQL_PASSWORD: password
    volumes:
      - mysql_data:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password

volumes:
  mysql_data:
  metabase_data: